Add 'main' in package.json
TylorShin/npm-module-es2015-boilerplate pull request #12
Opened 2016-09-28 16:52 UTC by LeeTaeSoon

Add 'main' in package.json and
add export default in index.js

2016-09-28 16:54 UTC, LeeTaeSoon commented
https://github.com/JeffGuKang/npm-webpack-boilerplate/issues/36
@JeffGuKang  Is this right?

2016-09-28 16:55 UTC, JeffGuKang commented on package.json
> +  "main": "index.js",
`src/index.js`

2016-09-28 16:56 UTC, JeffGuKang requested changes
`src/index.js` is right.

2016-09-28 17:13 UTC, LeeTaeSoon commented
Changed

2016-09-29 03:20 UTC, TylorShin commented
🍶

2016-09-29 03:20 UTC, merged